# Generated by Django 5.2.1 on 2025-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
